# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  schedule:  # at 03:06 on day-of-month 12
    - cron: '6 3 12 * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: ['14', '16', '18']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        exclude:
          # macos-latest does not have Node 14
          - os: macos-latest
            node-version: '14'

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run tests on Windows after setting HOME environment variable
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        $env:HOME = $env:HOMEPATH
        echo "Set HOME to $HOME"
        npm ci
        npm run test
    - name: Run tests on POSIX
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        npm ci
        npm run test
